---
- hosts: localhost
  gather_facts: no
  
  connection: local
  
  vars_files:
    - vars/main.yaml

  tasks:
    - name: "Upload an {{ avi_image_name }}: file: {{ avi_image_filename }}"
      os_image:
        auth:
          auth_url: "{{ auth.auth_url }}"
          username: "{{ auth.username }}"
          password: "{{ auth.password }}"
          project_name: "{{ auth.project_name }}"
          domain_name: "{{ auth.domain_name }}"
        name: "{{ avi_image_name }}"
        container_format: "{{ avi_image_containerfmt }}"
        disk_format: "{{ avi_image_format }}"
        state: "{{ state | default('present') }}"
        interface: "{{ avi_image_interface }}"
        filename: "{{ avi_image_filename }}"
      register: image_result

    - name: "Print image ID"
      debug:
        msg: "Image ID: {{ image_result }}"
