---
- hosts: localhost
  connection: local
  
  vars_files:
    - vars/main.yaml

  roles:
    - role: avinetworks.avisdk
  
  tasks:
    - name: Create a OpenStack cloud connector with write access mode
      avi_cloud:
        avi_credentials: "{{ avi_credentials }}"
        name: openstack
        tenant_ref: '/api/tenant/?name=admin'
        vtype: CLOUD_OPENSTACK
        openstack_configuration:
            auth_url: 'http://10.100.0.11:5000/v3'
            admin_tenant: avi
            name_owner: true
            map_admin_to_cloudadmin: true
            privilege: WRITE_ACCESS
            free_floatingips: true
            config_drive: true
            username: avi
            password: 'Avi123$%'
            insecure: false
            mgmt_network_name: avi_admin
            tenant_se: true
            anti_affinity: true
            use_keystone_auth: true
            import_keystone_tenants: true
            neutron_rbac: true
            hypervisor: KVM
            region: RegionOne
            use_admin_url: true
            img_format: OS_IMG_FMT_AUTO
            external_networks: false
            role_mapping:
                - 
                    avi_role: Tenant-Admin
                    os_role: admin
                - 
                    avi_role: Tenant-Admin
                    os_role: _member_
        ip6_autocfg_enabled: true
        dhcp_enabled: true

