---
- hosts: localhost
  gather_facts: no
  
  connection: local
  
  vars_files:
    - vars/main.yaml

  roles:
    - role: avinetworks.avisdk
  
  tasks:
    - name: Configure Service Engine Group "{{ se_group_name }}"
      avi_serviceenginegroup:
        avi_credentials: "{{ avi_credentials }}"
        se_name_prefix: "{{ se_name_prefix }}"
        auto_redistribute_active_standby_load: true
        bgp_state_update_interval: 10
        vs_scalein_timeout: 30
        placement_mode: "{{ placement_mode }}"
        max_scaleout_per_vs: "{{ max_scaleout_per_vs }}"
        per_app: false
        name: "{{ se_group_name }}"
        tenant: "{{ tenant_name_admin }}"
        max_se: "{{ max_se_seg }}"
        algo: "{{ se_vs_placement }}"
        realtime_se_metrics:
            duration: 30
            enabled: false
        extra_config_multiplier: 0
        async_ssl_threads: 2
        ssl_preprocess_sni_hostname: true
        max_cpu_usage: 80
        min_scaleout_per_vs: 1
        buffer_se: 1
        significant_log_throttle: 100
        min_se: 1
        instance_flavor: "{{ instance_flavor }}"
        se_thread_multiplier: 2
        max_vs_per_se: "{{ max_vs_per_se }}"
        #log_disksz: "{{ log_disksz }}"
        enable_vmac: false
        hm_on_standby: true
        cloud_ref: '/api/cloud?name={{ cloud_name }}'
        auto_rebalance: "{{ auto_rebalance | default('true') }}"
        auto_rebalance_interval: 300
