---
- hosts: localhost
  gather_facts: no
  
  connection: local
  
  vars_files:
    - vars/main.yaml

  roles:
    - role: avinetworks.avisdk
  
  tasks:
    - name: Create or Update Pool
      avi_pool:
        avi_credentials: "{{ avi_credentials }}"
        tenant: '{{ tenant_name }}'
        name: "web-pool"
        cloud_ref: "/api/cloud?name={{ cloud_name }}"
        health_monitor_refs:
          - '/api/healthmonitor?name=System-HTTP'
        servers:
          - ip:
              addr: '10.0.0.3'
              type: 'V4'
          - ip:
              addr: '10.0.0.4'
              type: 'V4'
