---
- hosts: localhost
  gather_facts: no
  
  connection: local
  
  vars_files:
    - vars/main.yaml

  roles:
    - role: avinetworks.avisdk
  
  tasks:
    - name: create servers to be used on Pool
      set_fact:
        pool_servers: "{{ pool_servers | default([]) + [{'ip': {'type': 'V4', 'addr': item }}]}}"
      loop: "{{ addresses }}"

    - name: Create or Update Pool
      avi_pool:
        avi_credentials: "{{ avi_credentials }}"
        tenant: '{{ tenant_name }}'
        name: "{{ pool_name }}"
        cloud_ref: "/api/cloud?name={{ cloud_name }}"
        health_monitor_refs:
          - '/api/healthmonitor?name={{ hm_name }}'
        servers: "{{ pool_servers }}"
