---
- hosts: localhost
  connection: local
  
  vars: 
    avi_credentials:
      controller: "10.150.0.9"
      username: "admin"
      password: "Avi123$%"
      api_version: "18.1.5"
    cloud_name: openstack
    tenant_name: demo

  roles:
    - role: avinetworks.avisdk
  
  tasks:
    - name: Create or Update Pool
      avi_pool:
        avi_credentials: "{{ avi_credentials }}"
        tenant: '{{ tenant_name }}'
        name: "web-pool"
        cloud_ref: "/api/cloud?name={{ cloud_name }}"
        health_monitor_refs:
          - '/api/healthmonitor?name=System-HTTP'
        servers:
          - ip:
              addr: '10.0.0.3'
              type: 'V4'
          - ip:
              addr: '10.0.0.4'
              type: 'V4'
