---
- hosts: localhost
  connection: local

  vars_files:
    - vars/main.yaml

  roles:
    - role: avinetworks.avisdk

  tasks:
    - name: Upload or Update SSL certificate
      avi_sslkeyandcertificate:
        avi_credentials: "{{ avi_credentials }}"
        tenant: demo
        key: "{{ lookup('file', key) }}"
        key_passphrase: '123456'
        certificate:
          certificate: "{{ lookup('file', cert)}}"
        type: SSL_CERTIFICATE_TYPE_VIRTUALSERVICE
        name: "{{ cert_name }}"


# ansible-playbook upload_cert_key.yaml -e "controller=192.168.0.27 username=admin password=Avi123$% cert_name=certname"

