---
- hosts: localhost
  gather_facts: no

  connection: local

  vars_files:
    - vars/main.yaml

  roles:
    - role: avinetworks.avisdk

  tasks:
    - name: Upload or Update SSL certificate
      avi_sslkeyandcertificate:
        avi_credentials: "{{ avi_credentials }}"
        tenant: demo
        key: "{{ lookup('file', key) }}"
        key_passphrase: "{{ key_passphrase }}"
        certificate:
          certificate: "{{ lookup('file', cert)}}"
        type: "{{ cert_type}}"
        name: "{{ cert_name }}"

# ansible-playbook upload_cert_key.yaml -e "controller=192.168.0.27 username=admin password=Avi123$% cert_name=certname"

