---
- hosts: localhost
  connection: local
  
  vars: 
    username: "admin"
    password: "Avi123$%"
    api_version: "18.1.5"
    old_password: "58NFaGDJm(PJH0G"

    nodes:
    - { name: 'server01' }
    - { name: 'server02' }

    rules:
    - { port: 22, protocol: 'tcp'}
    - { port: 80, protocol: 'tcp'}
    - { port: 443, protocol: 'tcp'}
    - { port: -1, protocol: 'icmp'}

    auth:
      auth_url: "http://10.100.0.11:5000/v3"
      username: demo
      password: Avi123$%
      project_name: demo
      domain_name: Default
    avi_image_name: ubuntu-xenial-server
    flavor_name: m1.tiny
    key_name: "llima3000"
    security_group_name: "webservers"
    az: nova
    network_name: private

  roles:
    - role: avinetworks.avisdk
  
  tasks:
    - name: Gather facts about Image "{{ avi_image_name }}"
      os_image_facts:
        auth: "{{ auth }}"
        image: "{{ avi_image_name }}"
      register: image_result
      # var: image_result['ansible_facts']['openstack_image']['id']

    - name: Gather facts about OpenStack flavor "{{ flavor_name }}" 
      os_flavor_facts:
        auth: "{{ auth }}"
        name: "{{ flavor_name }}"
      register: flavor_facts
      # var: flavor_facts['ansible_facts']['openstack_flavors'][0]['id']

    - name: Config security group for Controllers
      os_security_group:
        auth: "{{ auth }}"
        state: present
        name: "{{ security_group_name }}"
        description: security group for foo servers
      register: os_sec_group

    - name: Config roles in security group for Controllers
      os_security_group_rule:
        auth: "{{ auth }}"
        security_group: "{{ security_group_name }}"
        direction: ingress
        ethertype: IPv4
        protocol: "{{ item.protocol }}"
        port_range_min: "{{ item.port }}"
        port_range_max: "{{ item.port }}"
        remote_ip_prefix: 0.0.0.0/0
      loop: "{{ rules }}"

    - name: Launch an server instance
      os_server:
        state: present
        auth: "{{ auth }}"
        name: "{{ item.name }}"
        availability_zone: "{{ az }}"
        image: "{{ image_result['ansible_facts']['openstack_image']['id'] }}"
        key_name: "{{ key_name }}"
        timeout: 200
        flavor: "{{ flavor_facts['ansible_facts']['openstack_flavors'][0]['id'] }}"
        security_groups: "{{ security_group_name }}"
        #auto_ip: yes
        boot_from_volume: True
        volume_size: 5
        terminate_volume: True
        nics:
         - net-name: "{{ network_name }}"
      register: result
      loop: "{{ nodes }}"

